apiVersion: batch/v1
kind: Job
metadata:
  name: failing-job
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: example-app
        image: coryodaniel/example-app
        command: ["/example-app",  "-mode=job", "-job-force-fail"]