apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: example-app
spec:
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: example-app