---
# Note: CRD has become stable in k8s 1.16+ (apiextensions.k8s.io/v1)
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: todos.todo-operator.bonny.run
spec:
  group: todo-operator.bonny.run
  versions:
  - name: v1alpha1
    served: true
    storage: true
  names:
    kind: Todo
    plural: todos
  scope: Namespaced
  validation:
    openAPIV3Schema:
      description: Todo is a thing you need to get done.    
      type: object
      required:
      - apiVersion
      - kind
      - metadata
      - spec
      properties:
        apiVersion:
          description: >
            APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
          type: string
        kind:
          description: >
            Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
          type: string
        metadata:
          type: object
        spec:
          type: object
          required:
          - name
          - state
          properties:
            name:
              description: Name of the Todo task
              type: string
            details:
              description: Details of the Todo task
              type: string
            state:
              enum:
              - Pending
              - In progress
              - Blocked
              - Completed
              type: string
  additionalPrinterColumns:
    - JSONPath: .spec.state
      name: State
      type: string