---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotty
  labels:
    app: spotty
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: spotty
  template:
    metadata:
      labels:
        app: spotty
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - name: spotty
        image: coryodaniel/spotty-server:latest-debug
        env:
          - name: SPOTTY_ADDR
            value: "0.0.0.0"
          - name: SPOTTY_PORT
            value: "8080"
        ports:
        - name: web
          containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 50Mi
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: spotty
spec:
  type: NodePort
  selector:
    app: spotty
  ports:
  - port: 8080
    targetPort: web
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-quota
spec:
  hard:
    requests.cpu: 500m
    requests.memory: 500Mi
    limits.cpu: 2000m
    limits.memory: 1Gi
# ---
# apiVersion: v1
# kind: LimitRange
# metadata:
#   name: default-limit
# spec:
#   limits:
#   - max:
#       cpu: 1000m
#       memory: 500Mi
#     type: Container