---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotty
  labels:
    app: spotty
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: spotty
  template:
    metadata:
      labels:
        app: spotty
    spec:
      containers:
      - name: spotty
        image: coryodaniel/spotty-server:latest
        ports:
        - name: web
          containerPort: 8080
        resources:
          requests:
            cpu: 1500m
            memory: 50Mi
          limits:
            cpu: 1500m
            memory: 50Mi
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /spotty
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-quota
spec:
  hard:
    requests.cpu: 500m
    requests.memory: 500Mi
    limits.cpu: 2000m
    limits.memory: 1Gi