---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cpu-affinity
  name: cpu-affinity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-affinity
  template:
    metadata:
      labels:
        app: cpu-affinity
    spec:
      containers:
        - image: quay.io/coryodaniel/affinity:latest
          name: cpu-affinity
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 200m
              memory: 100Mi
