---
apiVersion: todo-operator.bonny.run/v1alpha1
kind: Todo
metadata:
  name: create-slideshow
spec:
  name: Create Slideshow
  description: |-
    * [x] Figure out topics
    * [x] Make some notes
    * [x] Create a theme
  state: Completed
---
apiVersion: todo-operator.bonny.run/v1alpha1
kind: Todo
metadata:
  name: create-demo
spec:
  name: Create Demo
  description: |-
    * [x] Example CRD
    * [ ] Example resources
    * [ ] Basic operator with elixir
  state: In progress  
