apiVersion: apps/v1
kind: Deployment
metadata:
  name: better-together
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 50%
  template:
    spec:
      terminationGracePeriodSeconds: 120
      containers:
        - name: better-together
          image: quay.io/coryodaniel/better_together:latest
          ports:
            - containerPort: 4000
              name: web
          env:
            - name: PORT
              value: "4000"
          resources:
            requests:
              cpu: 250m
              memory: 200Mi
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 60
            httpGet:
              path: /health
              port: 4000
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 60
            httpGet:
              path: /health
              port: 4000
