apiVersion: apps/v1
kind: Deployment
metadata:
  name: better-together
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: better-together
          image: quay.io/coryodaniel/better_together:latest
          ports:
            - containerPort: 4000
              name: web
          env:
            - name: PORT
              value: "4000"
          resources:
            limits:
              cpu: 500m
              memory: 200Mi
            requests:
              cpu: 500m
              memory: 200Mi
