---
apiVersion: v1
kind: Service
metadata:
  name: better-together-headless
spec:
  selector:
    app: better-together
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: better-together-web
spec:
  sessionAffinity: None
  type: NodePort
  ports:
    - name: web
      port: 4000
      targetPort: web
  selector:
    app: better-together
