---
apiVersion: todo-operator.bonny.run/v1
kind: Todo
metadata:
  name: make-stickers
spec:
  name: Make Stickers
  description: People wont like you otherwise.
  state: Completed
---
apiVersion: todo-operator.bonny.run/v1
kind: Todo
metadata:
  name: create-slideshow
spec:
  name: Create Slideshow
  description: |-
    * [x] Figure out topics
    * [x] Make some notes
    * [x] Create a theme
  state: Completed
---
apiVersion: todo-operator.bonny.run/v1
kind: Todo
metadata:
  name: create-demo
spec:
  name: Create Demo
  description: |-
    * [x] Example CRD
    * [x] Example resources
    * [x] Basic operator with elixir
    * [ ] Embarrass self
  state: In progress  
---
apiVersion: todo-operator.bonny.run/v1
kind: Todo
metadata:
  name: live-demo
spec:
  name: Live Demo
  description: |-
    * [ ] BREATHE    
    * [ ] Deploy a CRD
    * [ ] Create some todos
    * [ ] List todos
    * [ ] Get todo
    * [ ] Cleanup
    * [ ] Show bonny controller
    * [ ] deploy manifest
    * [ ] stern them logs
    * [ ] re-apply yaml/todos.yaml
  state: In progress  
